import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import dynamic from "next/dynamic";
const WalletConnectionProvider=dynamic(()=>import("@/context/WalletContextProvider"),{
  ssr:false,
});

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
        <WalletConnectionProvider>
          {children}
        </WalletConnectionProvider>
        </main>
      </body>
    </html>
  );
}
